### ISSUE TITLE
Request for new PyPI release

### ISSUE THREAD

**Issue by bennahugo** [jraedler/Polygon3#1]
@jraedler is it possible to push a release of master?

I'm getting a pickling error of the cPolygon submodule with multiprocessing for the release version of Polygon3 which has been fixed in master
```
Traceback (most recent call last):
  File "/home/hugo/workspace/venv3/bin/ClusterCat.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/hugo/workspace/DDFacet/SkyModel/ClusterCat.py", line 340, in <module>
    main(options=options)
  File "/home/hugo/workspace/DDFacet/SkyModel/ClusterCat.py", line 332, in main
    CIM.Cluster()
  File "/home/hugo/workspace/DDFacet/SkyModel/ClusterCat.py", line 277, in Cluster
    xyNodes,self.LPolygon=CC.Cluster()
  File "/home/hugo/workspace/DDFacet/SkyModel/Sky/ClassClusterDEAP.py", line 244, in Cluster
    halloffame=hof,PlotMachine=PlotMachine)
  File "/home/hugo/workspace/DDFacet/SkyModel/Sky/DeapAlgo.py", line 190, in eaSimple
    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f1bd3720c18>'. Reason: 'PicklingError("Can't pickle <class 'cPolygon.Error'>: import of module 'cPolygon' failed",)'
```

I would much appreciate if you can assist with this, because without it I cannot push a pypi release of our software (PyPI does not allow installation from git to be pushed)

**Comment by jraedler** [comment]
I uploaded a new source distribution to PyPi from the current master branch. It's called 3.0.9.1 (3.0.9 was broken, but can't be replaced). Does this solve your problem?
I will upload new binaries in the next weeks when I find the time.

**Comment by bennahugo** [comment]
Hi @jraedler. Thanks a lot for pushing an sdist. It successfully builds a wheel in a fresh virtualenv. However I get the same error when run

I have fetched the latest master and installed that using ```pip install -U ./Polygon3``` and this works fine. So I'm a bit stumped - I think this means something about cPolygon is not included in the sdist and bdist manifests?

**Comment by bennahugo** [comment]
I will try put together a reproducer for this.

**Comment by bennahugo** [comment]
@jraedler I'm going to close this - it seems the pickling error is a red herring. It only happens when there is an intermittent exception being raised on a child process in the codebase I'm working on. If I run it in serial I get the actual error being raised. Thanks for pushing a new release of the package
